### ISSUE TITLE
PSM1000 - Connection issue since Companion v3.X.X

### ISSUE THREAD

**Issue by pylaflamme** [bitfocus/companion-module-shure-psm1000#7]
Hello everyone!

I was running the instance for a SHURE PSM1000 on a Companion v2.4.1 without any problem. I had the full control of the device, and all the feedbacks and variables were 100% available. I did the upgrade to Companion v3 and since than the instance was not working anymore, so I tried to downgrade to the previous v2.4.1 of Companion and everything was functional again.

![Screen Shot 2024-07-11 at 11 22 31 PM](https://github.com/user-attachments/assets/686ef814-99ba-4d98-b1f8-82bc33bbc0b7)

I thought maybe it was a problem with my computer, so I tried with a Companion v3 on a different computer and on a Raspberry Pi and same problem, Companion v3 is not working anymore with the SHURE PSM1000...

Can someone help me with that??

**Comment by krocheck** [comment]
@pylaflamme Can you click the >_ icon to view the module's console log to see what/if any errors are showing up.

**Comment by xoir** [comment]
Can confirm. PSM1000 is pingable from the computer companion 3.40 is running on but I am unable to start a connection. 

See log for details: [module-log-28.8.2024-17_56_03.csv](https://github.com/user-attachments/files/16785949/module-log-28.8.2024-17_56_03.csv)

Shure AD-Series on the same network is working fine.

**Comment by krocheck** [comment]
@xoir Would you be willing to do an "Export Support Bundle" from the Logs tab and upload it [here](https://www.dropbox.com/request/XH8ODlUpwrVYJlGSFcz3)

The errors imply the module can't load the configuration fields, but I am not able to reproduce that both on my dev machine and with the downloads from the Bitfocus website.

**Comment by xoir** [comment]
done

**Comment by krocheck** [comment]
I think I got it.  There will be a new beta compiled within the next 6 or so hours with v2.0.3 of the module with a fix.

**Comment by xoir** [comment]
Fixed it for me! Thank you a lot!

**Comment by pylaflamme** [comment]
> I think I got it.  There will be a new beta compiled within the next 6 or so hours with v2.0.3 of the module with a fix.

Thanks for your help!!
I'm actually not on tour with my wireless rack with the PSM1000, but I'll try it in the next weeks and I'll let you know!
Thanks again, it's really helpful and appreciated!
